name: Mentions

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, review_requested]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Github mention to Slack
        uses: abeyuya/actions-mention-to-slack@v2.4
        with:
          # Mapping config for Github username to Slack member ID.
          #configuration-path: # default is .github/mention-to-slack.yml
          # Slack Incomming Webhook URL to notify.
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          # Github access token to fetch .github/mention-to-slack.yml file.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Display name for this bot on Slack.
          bot-name: "Send Mention from abeyuya/actions-mention-to-slack" # optional
          # Display icon url for this bot on Slack.
          icon-url: https://img.icons8.com/color/256/000000/github-2.png # optional
                     
